# -*- coding: utf-8 -*-
"""ЦК_ДЗ_Визуализация_+_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aFGEfg4rqnKga6BaoR8VcdYgiAF81wwb

# Задание по визуализации

Ссылка на данные: https://drive.google.com/drive/folders/1by7kkSwB-uMgIKKwEU-U_i81MnxMR4oM?usp=sharing

## Вариант 1

**Задания:**
1. Постройте Диаграмму разброса (точечный график) от двух переменных: `Vmag` и `e_Plx`.
2. Построить график анализа пропущенных значений.
3. Построить boxplot для всех числовых переменных. График должен быть один, используя разные subplot() для каждой переменной (т.е. одна фигура и несколько сабплотов).
4. Построить barplot по переменной `TargetClass`.
5. Построить матрицу корреляции для всех переменных.
6. Построить графики парных зависимостей между всеми числовыми переменными (если много переменных, возьмите только часть).
7. Построить график распределения любой переменной.

*P.s. Все графики, оси и переменные должны быть подписаны. И по графикам необходимо сделать выводы.*

**Датасет для задания называется train_var1.csv**
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("train_var_1.csv")

# ваше решение

"""**Задание 1**"""

x = df["Vmag"]
y = df["e_Plx"]
x.shape, y.shape

x = df["Vmag"]
y = df["e_Plx"]
fig, ax = plt.subplots()

ax.scatter(x, y, c = '#FF00FF', s = 1)

ax.set_xlabel("Это Vmag")
ax.set_ylabel("А это не Vmag, это e_Plx")
ax.set_title("Это разброс V_mag и e_Plx")
ax.set_facecolor('yellow')     #  цвет области Axes

fig.set_figwidth(6)
fig.set_figheight(6)
plt.show()

"""Можно заметить, что с ростом Vmag все сильнее проявляется положительная корреляция

**Задание 2**
"""

df.isna().sum()

plt.figure(figsize=(5,5))
sns.displot(
    data=df.isna().melt(value_name="is_missing"),
    y="variable",
    hue="is_missing",
    multiple = "fill",
    aspect=1.25)

"""Пропусков в датасете нет

Задание 3
"""

df.select_dtypes(include=['number'])

fig, axes = plt.subplots(2, 3, figsize=(10,10))
fig.tight_layout(pad = 2)
n = 0.2

# ax[0].scatter()
sns.boxplot(df['Vmag'], ax=axes[0, 0], width=n)
sns.boxplot(df['Plx'], ax=axes[0, 1], width=n)
sns.boxplot(df['e_Plx'], ax=axes[0, 2], width=n)
sns.boxplot(df['B-V'], ax=axes[1, 0], width=n)
sns.boxplot(df['Amag'], ax=axes[1, 1], width=n)
sns.boxplot(df['TargetClass'], ax=axes[1, 2], width=n)

"""Аномалий нет в столбце TargetClass, так как значения в нем принимают либо 1 либо 0. Также не так много аномлий, но они есть в B-V. Остальные же параметры включают огромное значение аномалий, особенно Plx и e_Plx

Задание 4
"""

plt.title('TargetClass')
plt.xlabel('Значение')
plt.ylabel('Количество')
sns.countplot(x='TargetClass', data=df)

"""TargetClass принимает значения 1 и 0 примерно поровну

Задание 5
"""

plt.figure(figsize=(10,6))

corr_matrix = df.corr(numeric_only=True)
sns.heatmap(corr_matrix, xticklabels=df.corr(numeric_only=True).columns, yticklabels=df.corr(numeric_only=True).columns, cmap='Reds', center=0, annot=True)
# color pallete sns
# Decorations
plt.title('Корреляция', fontsize=22)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)
plt.show()

"""В большинстве случаев наблюдается околонулевая корреляция, однако между параметрами Amag и Plx, Vmag и e_Plx, Amag и TargetClass видна положительная корреляция приближенная к 0.5 у Amag и Plx- 0.64. Также параметры B-V и TargetClass имеют отрицательную корреляцию в -0.55

Задача 6
"""

plt.figure(figsize=(10, 10))
ddf = df.select_dtypes(include='number')
sns.pairplot(ddf, kind='reg', hue = 'TargetClass')
plt.show

"""Результаты схожи с матрицей корреляции

Задание 7
"""

plt.title('Vmag')
sns.distplot(df['Vmag'], bins=20)

"""Биноминальное распределение"""